### ISSUE TITLE
Hammering hangs with --no-refresh

### ISSUE THREAD

**Issue by matteo-sammartino** [antmicro/rowhammer-tester#180]
Hi, I am using a ZCU104 board and the latest version of the repo.

When I try to run the following command from the user guide
```shell
python hw_rowhammer.py --nrows 512 --read_count 10e6 --pattern 01_in_row --row-pairs const --const-rows-pair 54 133 --no-refresh
```
it hangs here:
![image](https://github.com/antmicro/rowhammer-tester/assets/5467613/2b538fb7-a8bd-4331-b44e-c34906f1ccda)
and after Ctrl-C-ing no other command works, at which point I need to reboot the ZCU104 board.

It works fine without the --no-refresh flag.

**Comment by mtdudek** [comment]
Hi, I believed we solved this issue in the newest update.
I've tested it on arty and ddr5 tester boards.
