### ISSUE TITLE
Change Memory Mapping to BANK-ROW-COL from ROW-BANK-COL: Impact on DMA Writing?

### ISSUE THREAD

**Issue by biecho** [antmicro/rowhammer-tester#186]
**Is there a way to change the memory mapping of the Memory Controller (MC) to `BANK-ROW-COL` instead of the default `ROW-BANK-COL` mapping?**

I have a set of rows within the same bank that should be initialized with the same data pattern (0xFFFFFFFF) as fast as possible. With the current ROW-BANK-COL mapping, I suspect that DMA performance could be suboptimal, as DMA operations are spread across multiple rows before completing operations within the target bank.

1. **Is it possible to change the memory mapping of the MC to `BANK-ROW-COL`?**
2. **Are there specific configurations, registers, or hardware limitations to consider when doing this?**
3. **Are there other alternatives to achieve this goal?**

**Comment by wkkuna** [comment]
Hi @biecho,

> Is it possible to change the memory mapping of the MC to BANK-ROW-COL?

We've recently added the support for `BANK-ROW-COL` mapping.
The addressing needs to be specified at the build stage of the design.
It suffices to append the `--address-mapping=BANK_ROW_COL` option to the `ARGS` enviromental variable before performing the `make build` step.

> Are there specific configurations, registers, or hardware limitations to consider when doing this?

None that we're aware of.

> Are there other alternatives to achieve this goal?

No, the address mapping is tightly encoupled with the DRAM Controller.
