### ISSUE TITLE
The RefreshCounter in Payload executor is 32-bits

### ISSUE THREAD

**Issue by sqazi** [antmicro/rowhammer-tester#193]
Hi,

Longer running tests using the at_refresh feature can get discrepancies in their behavior when the counter overflows.  This takes about 4 hours.  Would it be possible to expand this to 64 bits to avoid this situation?

**Comment by pjattke** [comment]
A question related to this: if we disable the memory controller-issued REFs right before the memory training, we still always observe around 3.5M REFs after the FPGA booted up. Do we correctly assume that this means the FPGA starts sendings REFs to the DRAM device immediately after booting up (already before the memory training started)?
