### ISSUE TITLE
ReadTheDocs documentation doesn't clearly link back to the GitHub repository

### ISSUE THREAD

**Issue by mithro** [antmicro/rowhammer-tester#76]
I wasn't able to find a quick way to go from https://litex-rowhammer-tester.readthedocs.io/en/latest/general.html to this repository.

**Comment by kgugala** [comment]
Now we have `View repository on GitHub` button in the upper right corner:

![image](https://user-images.githubusercontent.com/3785621/148266910-47b03777-1b28-465f-9e5a-f6958519bff2.png)
